---
- name: Add users on servers
  hosts: if                                                 #введи группу хостов
  become: yes

  vars:
    docker_compose: no                                      #если нужен компоусе поставить yes


  tasks:

  - name: Check Linux Version
    debug: var=ansible_os_family

  block:     # =========Block for Debian========

  - name: Update and Upgrade repo
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: Install packages
    apt: name:{{ item }} state:latest
    loop:
      - fail2ban
      - htop
      - mc
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https

  - name: Install Docker-compose
    shell: {{ item }}
    loop:
      - curl -SL https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - chmod a+x /usr/local/bin/docker-compose
      - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    when: {{ docker_compose }} == "yes"


  when: ansible_os_family == "Debian"
